/usr/bin/python3 util/sweep_garnet_injection.py \
    --gem5-bin ./build/NULL/gem5.opt \
    --config configs/example/garnet_synth_traffic.py \
    --extractor util/extract_garnet_stats.py \
    --num-cpus 4 \
    --num-dirs 4 \
    --network garnet \
    --topology Mesh_XY \
    --mesh-rows 2 \
    --sim-cycles 10000000 \
    --synthetic uniform_random \
    --min-rate 0 \
    --max-rate 1 \
    --coarse-step 0.01 \
    --max-fine-intervals 0 \
    --workdir m5out/sweep_step_0p01_uniform \
    --force-rerun
